<h1>Members List</h1>
<div class="row">
<div class="col-xs-12 col-sm-6 col-sm-offset-3">

<?php if ($this->user): ?>
<table class="table">
	<caption>Users in our app</caption>
	<thead>
		<tr>
			<th>#id</th>
			<th>Email</th>
			<th>Username</th>
			<th>Created at</th>
		</tr>
	</thead>
	<tbody>
	<?php if (isset($this->members) && count($this->members)): ?>
	<?php foreach ($this->members as $key => $user): ?>
		<tr>
			<td><?= $this->escapeHtml($user->getId()); ?></td>
			<td><?= $this->escapeHtml($user->getEmail()); ?></td>
			<td><?= $this->escapeHtml($user->getUsername()); ?></td>
			<td><?= $this->escapeHtml($user->getCreatedAt()); ?></td>
		</tr>		
	<?php endforeach ?>
	<?php endif ?>
	</tbody>
</table>



<?php if ($this->paginationData->current > $this->paginationData->first): ?>
	<a href="<?= $this->url('members', ['page'=>$this->paginationData->previous]) ?>" title=""> Previous Page</a>&nbsp;
<?php endif ?>

<?php if ($this->paginationData->current < $this->paginationData->pageCount): ?>
	<a href="<?= $this->url('members', ['page'=>$this->paginationData->next]) ?>" title="">Next Page</a>
<?php endif ?>

<?php else: ?>
	<p class="alert alert-info"><a href="<?= $this->url('loginForm') ?>">Login</a> to view this page</p>
<?php endif; ?>



</div>
</div>