<?php 
	$form = $this->form;
	$form->setAttribute('action', $this->url('signupForm'));
	$form->prepare();
	$messages = $form->getMessages();
 ?>

<h1>Signup form</h1>

<div class="row">
<div class="col-xs-12 col-sm-6 col-sm-offset-3">
	
<?php if (isset($this->userExists) && $this->userExists === true): ?>
	<p class="alert alert-danger">User with this email already exists</p>	
<?php endif ?>


<?= $this->form()->openTag($form) ?>

	<div class="form-group">
		<?= $this->formLabel($form->get('email')); ?>
		<?= $this->formElement($form->get('email')); ?>		 

		<?php if (isset($messages['email']) && $messages['email']): ?>
			<p class="alert alert-warning">
			<?php foreach ($messages['email'] as $rule => $msg): ?>
	 			<?= $msg ?>
			<?php endforeach ?>
			</p>
		<?php endif ?>   
	</div>

	<div class="form-group">
		<?= $this->formLabel($form->get('username')); ?>
		<?= $this->formElement($form->get('username')); ?>	

		<?php if (isset($messages['username']) && $messages['username']): ?>
			<p class="alert alert-warning">
			<?php foreach ($messages['username'] as $rule => $msg): ?>
		 			<?= $msg ?>
			<?php endforeach ?>
			</p>
		<?php endif ?>   	 	 	 
	</div>


	<div class="form-group">
	<?= $this->formLabel($form->get('password')); ?>
	<?= $this->formElement($form->get('password')); ?>		 
	<?php if (isset($messages['password']) && $messages['password']): ?>
			<p class="alert alert-warning">
		<?php foreach ($messages['password'] as $rule => $msg): ?>
	 			<?= $msg ?>
		<?php endforeach ?>
			</p>
		<?php endif ?>  	 
	</div>

	 <div class="form-group">
		<?= $this->formLabel($form->get('password_repeat')); ?>
	    <?= $this->formElement($form->get('password_repeat')); ?>		 
		<?php if (isset($messages['password_repeat']) && $messages['password_repeat']): ?>
	 		<p class="alert alert-warning">
			<?php foreach ($messages['password_repeat'] as $rule => $msg): ?>
		 			<?= $msg ?>
			<?php endforeach ?>
	 		</p>
	   	<?php endif ?> 
	</div>

	<div class="form-group">
		<?= $this->formElement($form->get('captcha')); ?>
		<?= $this->formElementErrors($form->get('captcha')); ?>
		<p class="help-block">Enter the letters above as you see them.</p>
	</div>


	<div class="form-group">
		<div class="form-group col-xs-12 col-sm-7 col-sm-offset-2">
			<?= $this->formRow($form->get('submit')) ?>

	 	</div>
	 </div>


<?= $this->form()->closeTag(); ?>
</div>
</div>
